const hurdlers = {
    boys: [
        {
            first: "Jack",
            last: "Guscette",
            grade: 11,
            high: true,
            low: true,
        },
        {
            first: "Desire",
            last: "Masiri",
            grade: 11,
            high: true,
            low: true,
        },
        {
            first: "Joaquin",
            last: "Valdez",
            grade: 9,
            high: true,
            low: true,
        },
        {
            first: "Elijah",
            last: "Morris",
            grade: 10,
            high: true,
            low: true,
        },
        {
            first: "Bradyn",
            last: "Stockert",
            grade: 12,
            high: true,
            low: true,
        },
        {
            first: "Zander",
            last: "Senger",
            grade: 10,
            high: true,
            low: true,
        },
        {
            first: "Rory",
            last: "Senger",
            grade: 10,
            high: true,
            low: true,
        },
        {
            first: "Mag",
            last: "Cummings",
            grade: 11,
            high: true,
            low: true,
        },
        {
            first: "Keyton",
            last: "McGregor",
            grade: 12,
            high: true,
            low: false,
        },
    ],
    girls: [
        {
            first: "Brooke",
            last: "Finn",
            grade: 10,
            high: true,
            low: true,
        },
        {
            first: "Emma",
            last: "Esposito",
            grade: 10,
            high: true,
            low: true,
        },
        {
            first: "Soludo",
            last: "Obi",
            grade: 10,
            high: true,
            low: true,
        },
        {
            first: "McKenna",
            last: "Gross",
            grade: 10,
            high: true,
            low: true,
        },
        {
            first: "Ariana",
            last: "Gardner",
            grade: 11,
            high: false,
            low: true,
        },
        {
            first: "Lyla",
            last: "Fiechtner",
            grade: 11,
            high: true,
            low: true,
        },
        {
            first: "Michelle",
            last: "Gee",
            grade: 10,
            high: false,
            low: false,
        },
        {
            first: "Kadi",
            last: "Sacko",
            grade: 12,
            high: true,
            low: true,
        },
        {
            first: "Rylee",
            last: "Larson",
            grade: 11,
            high: false,
            low: true,
        },
        {
            first: "Katelyn",
            last: "Lowenberg",
            grade: 10,
            high: false,
            low: true,
        },
        {
            first: "Harnoor",
            last: "Johal",
            grade: 10,
            high: false,
            low: true,
        },
        {
            first: "Berthina",
            last: "Caesar",
            grade: 11,
            high: true,
            low: false,
        },
        {
            first: "Delaney",
            last: "Augdahl",
            grade: 10,
            high: true,
            low: false,
        },
        {
            first: "Emily",
            last: "Simek",
            grade: 10,
            high: false,
            low: true,
        },
    ]
}
