const jumpers = {
  boys: [
    // {
    //     first: "Keyton",
    //     last: "McGregor",
    //     grade: 12,
    //     long: true,
    //     triple: false,
    // },
    {
      first: "Joaquin",
      last: "Valdez",
      grade: 9,
      long: true,
      triple: true,
    },
    {
      first: "Lincoln",
      last: "Walker",
      grade: 10,
      long: true,
      triple: true,
    },
    {
      first: "Desire",
      last: "Masiri",
      grade: 11,
      long: true,
      triple: true,
    },
    {
      first: "Bradyn",
      last: "Stockert",
      grade: 12,
      long: false,
      triple: true,
    },
    {
      first: "Mag",
      last: "Cummings",
      grade: 11,
      long: true,
      triple: true,
    },
    {
      first: "Andrew",
      last: "Karr",
      grade: 11,
      long: true,
      triple: false,
    },
    {
      first: "Payton",
      last: "Schaan",
      grade: 10,
      long: true,
      triple: false,
    },
    {
      first: "Anthony",
      last: "Alonzo",
      grade: 12,
      long: true,
      triple: true,
    },
    {
      first: "Isaiah",
      last: "Perez",
      grade: 9,
      long: true,
      triple: true,
    },
    {
      first: "Ben",
      last: "Orvik",
      grade: 9,
      long: true,
      triple: true,
    },
    {
      first: "Luis",
      last: "Franssen",
      grade: 9,
      long: true,
      triple: false,
    },
    {
      first: "Ahmed",
      last: "Falir",
      grade: 12,
      long: true,
      triple: false,
    },
    {
      first: "Lance",
      last: "Williams",
      grade: 11,
      long: true,
      triple: false,
    },
    {
      first: "Jack",
      last: "Guscette",
      grade: 11,
      long: true,
      triple: false,
    },
    {
      first: "Eli",
      last: "Morris",
      grade: 10,
      long: true,
      triple: false,
    },
  ],
  girls: [
    {
      first: "Soludo",
      last: "Obi",
      grade: 10,
      long: true,
      triple: true,
    },
    {
      first: "Meghan",
      last: "Esposito",
      grade: 12,
      long: true,
      triple: true,
    },
    {
      first: "Hailey",
      last: "Metcalf",
      grade: 12,
      long: true,
      triple: false,
    },
    {
      first: "Berthina",
      last: "Caesar",
      grade: 11,
      long: true,
      triple: false,
    },
    {
      first: "McKenna",
      last: "Gross",
      grade: 10,
      long: true,
      triple: false,
    },
    {
      first: "Riley",
      last: "Larson",
      grade: 11,
      long: true,
      triple: false,
    },
    {
      first: "Emily",
      last: "Simek",
      grade: 11,
      long: true,
      triple: false,
    },
    {
      first: "Emma",
      last: "Esposito",
      grade: 10,
      long: true,
      triple: false,
    },
    {
      first: "Michelle",
      last: "Gee",
      grade: 10,
      long: true,
      triple: false,
    },
  ],
};
