const jumpers = {
  boys: [
    {
      first: "Joaquin",
      last: "Valdez",
      grade: 9,
      long: true,
      triple: false,
      approach: "81-7",
    },
    {
      first: "Desire",
      last: "Masiri",
      grade: 11,
      long: true,
      triple: true,
      approach: "85-3",
    },
    {
      first: "Lincoln",
      last: "Walker",
      grade: 10,
      long: false,
      triple: true,
      approach: "79-0",
    },
    {
      first: "Ben",
      last: "Orvik",
      grade: 9,
      long: true,
      triple: false,
      approach: "75-9",
    },
    {
      first: "Bradyn",
      last: "Stockert",
      grade: 12,
      long: false,
      triple: true,
      approach: "77-7",
    },
    {
      first: "Lance",
      last: "Williams",
      grade: 11,
      long: true,
      triple: false,
      approach: "84-8",
    },
    {
      first: "Jack",
      last: "Guscette",
      grade: 11,
      long: true,
      triple: true,
      approach: "89-9",
    },
    {
      first: "Eli",
      last: "Morris",
      grade: 10,
      long: true,
      triple: false,
      approach: "81-8",
    },
    {
      first: "Andrew",
      last: "Karr",
      grade: 11,
      long: true,
      triple: false,
      approach: "79-3",
    },
    {
      first: "Payton",
      last: "Schaan",
      grade: 10,
      long: true,
      triple: true,
      approach: "81-9",
    },
    {
      first: "Anthony",
      last: "Alonzo",
      grade: 12,
      long: false,
      triple: false,
      approach: "75",
    },
    {
      first: "Isaiah",
      last: "Perez",
      grade: 9,
      long: true,
      triple: true,
      approach: "75-0",
    },
    {
      first: "Mag",
      last: "Cummings",
      grade: 11,
      long: true,
      triple: true,
      approach: "84-6",
    },
    {
      first: "Ahmed",
      last: "Falir",
      grade: 12,
      long: true,
      triple: true,
      approach: "77-7",
    },
    {
      first: "Horatio",
      last: "Willie",
      grade: 11,
      long: true,
      triple: true,
      approach: "77-7",
    },
    {
      first: "Bonfas",
      last: "Loria",
      grade: 11,
      long: true,
      triple: false,
      approach: "90-0",
    },
    {
      first: "Baskal",
      last: "Makuag",
      grade: 11,
      long: false,
      triple: true,
      approach: "75-0",
    },
    {
      first: "Cedric",
      last: "Patterson",
      grade: 10,
      long: true,
      triple: false,
      approach: "85-0",
    },
    {
      first: "Keyshawn",
      last: "Noah",
      grade: 10,
      long: true,
      triple: false,
      approach: "76-0",
    },
  ],
  girls: [
    {
      first: "Soludo",
      last: "Obi",
      grade: 10,
      long: true,
      triple: true,
      approach: "79-0 || 65-6",
    },
    {
      first: "Meghan",
      last: "Esposito",
      grade: 12,
      long: true,
      triple: true,
      approach: "79-5 || 65-6",
    },
    {
      first: "McKenna",
      last: "Gross",
      grade: 10,
      long: true,
      triple: false,
      approach: "64-9",
    },
    {
      first: "Riley",
      last: "Larson",
      grade: 11,
      long: false,
      triple: false,
    },
    {
      first: "Emily",
      last: "Simek",
      grade: 11,
      long: true,
      triple: false,
      approach: "63-0",
    },
    {
      first: "Emma",
      last: "Esposito",
      grade: 10,
      long: true,
      triple: true,
      approach: "66‐0",
    },
    {
      first: "Michelle",
      last: "Gee",
      grade: 10,
      long: true,
      triple: false,
      approach: "81-9",
    },
    {
      first: "Hailey",
      last: "Metcalf",
      grade: 12,
      long: true,
      triple: false,
      approach: "55-8",
    },
    {
      first: "Berthina",
      last: "Caesar",
      grade: 11,
      long: false,
      triple: false,
      approach: "63-8",
    },
    {
      first: "Brooklyn",
      last: "Kleingartner",
      grade: 10,
      long: false,
      triple: false,
      approach: "57-9",
    },
    {
      first: "Ejatu",
      last: "Bah",
      grade: 11,
      long: true,
      triple: true,
      approach: "66-0",
    },
    {
      first: "Hallie",
      last: "Pritchard",
      grade: 9,
      long: false,
      triple: false,
      approach: "61-0",
    },
    {
      first: "Ayla",
      last: "Ridl",
      grade: 9,
      long: true,
      triple: false,
      approach: "69-0",
    },
  ],
};
