const sprinters = {
    boys: [
        {
            first: "Ian",
            last: "Skari",
            grade: 9,
            100: true,
            200: true,
            400: true,
            4100: true,
            4200: true,
            4400: true,
        },
        {
            first: "Ibrahim",
            last: "Bangura",
            grade: 10,
            100: true,
            200: true,
            400: true,
            4100: true,
            4200: true,
            4400: true,
        },
        {
            first: "Isaac",
            last: "Nyenabo",
            grade: 12,
            100: true,
            200: true,
            400: false,
            4100: true,
            4200: true,
            4400: false,
        },
    ],
    girls: [
        {
            first: "Michelle",
            last: "Gee",
            grade: 9,
            100: true,
            200: true,
            400: true,
            4100: true,
            4200: true,
            4400: true,
        },
        {
            first: "Ella",
            last: "Heilman",
            grade: 10,
            100: true,
            200: true,
            400: true,
            4100: true,
            4200: true,
            4400: true,
        },
        {
            first: "Zevina",
            last: "Scarbrough",
            grade: 10,
            100: true,
            200: true,
            400: true,
            4100: true,
            4200: true,
            4400: true,
        },
    ]
}